[project]
name = "fastapi-cicd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Matin", email = "ali_matin16@yahoo.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.141.1",
    "uvicorn>=0.52.4",
]

[project.scripts]
fastapi-cicd = "fastapi_cicd:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
